#### Checking Records those are Matching Name of Students Who are Not Registered for Event/Workshop & Generarting their Contact Numbers

In [1]:
# Import required libraries
import pandas as pd
import numpy as np

In [2]:
%pwd

'C:\\Users\\pycoder\\21_All_Python\\21_ADataScience-Training\\Week-3'

In [3]:
root_path = 'C:/Users/pycoder/21_All_Python/21_ADataScience-Training/Week-3/'

### Uploading the Source Files

In [4]:
Apex21BDA1 = pd.read_excel(root_path + '20BDA1_Rough.xlsx')
Apex21BDA2 = pd.read_csv(root_path + '20BDA2_Rough.csv')
Apex21BDA3 = pd.read_excel(root_path + '20BDA3_Rough.xlsx')

In [4]:
#Apex20BDA1 = pd.read_csv(root_path + '20BDA1.csv')
#Apex20BDA2 = pd.read_csv(root_path + '20BDA2.csv')
#Apex20BDA3 = pd.read_csv(root_path + '20BDA3.csv')

#### Checking whether Uploaded Correctly or Not

In [5]:
type(Apex21BDA1)

pandas.core.frame.DataFrame

In [6]:
Apex21BDA1.head()

   Sr. No     Student Name Student UID    Section Group  Mobile Number
0       1  Tamanpreet Kaur   20BCS3754  20AITBDA1     A        8679508
1       2       Akash Siby   20BCS3757  20AITBDA1     A        8679508
2       3     Aditya Arora   20BCS3758  20AITBDA1     A        8679508
3       4      Iram Nishat   20bcs3761  20AITBDA1     A        8679508
4       5  Karan Bhandari    20BCS3763  20AITBDA1     A        8679508

In [8]:
Apex21BDA1.columns

Index(['Sr. No', 'Student Name', 'Student UID', 'Section', 'Group',
       'Mobile Number'],
      dtype='object')

In [10]:
Apex21BDA1['Student Name']

0               Tamanpreet Kaur
1                    Akash Siby
2                  Aditya Arora
3                   Iram Nishat
4               Karan Bhandari
5                    Salvin rai
6                    Amit Kumar
7              Abhinav Shreshth
8              Upesh Kumar Soni
9                 Vishal Mishra
10          VIKASH Kumar Mishra
11                  Reena Rewri
12                 Faizan Aslam
13           uma shankar singh
14                  Sahil Verma
15                  Leena Singh
16                MD AASIM RAZA
17              Aashiv Dhankhar
18                  varun singh
19                 Sagar Grover
20        Ashutosh Kumar Singh
21                Sushant kumar
22              Harshit chauhan
23          Chandrabhushankumar
24              Ketan Chhirolya
25               Tanish Vermani
26                 Prince Tomar
27                Sachin Pareek
28                Abhishek Rana
29            Harshdeep Bhinder
                ...
47                   Dev Sirohi
48                   Arpit Sood
49          Akshay Pratap Singh
50               Anshika Sharma
51                Ayush Acharya
52             Nileshâ€™s pandey
53                Sarthak Singh
54               B NAVEEN REDDY
55             Yug Pratap Gupta
56                 Aditya Yadav
57                Ayush paliwal
58                Piyush shukla
59               Abhinav Sharma
60            APOORV NAYAN DAS
61                 AFRIDI HAQUE
62       Kakkirala lohith kumar
63    MALLIREDDY RAVINDRA REDDY
64               Ashutosh kumar
65                  Sumit arora
66           Akshat Shrivastava
67                  Laksh Walia
68                 Aditya Bohra
69              Devyanshi Bohra
70            Diwakaran Agrawal
71                  Sahil Lodha
72                       Shruti
73                      Mallika
74               Prabhjot Singh
75               Chinmay Sharma
76                    Anshumaan
Name: Student Name, Length: 77, dtype: object

### Uploading Required File to which Maching Students Contacts Needed

In [11]:
Non_RegisteredStuds = pd.read_excel(root_path + '20BDA_Non_Registered_Rough.xlsx')

#### Checking for Successful Upload of file

In [12]:
Non_RegisteredStuds.head()

,Acct. No,Name,Father Name,City,Program Name,Academic Registered,hostel Name,Room No,Hostel Reported,Final Status,Unnamed: 10,Unnamed: 11
0,12023896,Bhavik Jain,Dilip jain,Raipur,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 3,523-C,Non-Reported,Non-Registered,NaN,"Asking for Fee pay in Installments, Bcoz Not A..."
1,12007223,MUKESH KUMAR,BRIJ BIHARI SINGH,Patna,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifted Call
2,12022636,Drishti Vashisth,Rajesh Sharma,Panchkula,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not Connecting
3,12006710,SAGAR GROVER,SATISH KUMAR,Chandigarh,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
4,12022639,TARUN BISHT,DEEP SINGH,Chandigarh,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifted Call

#### Considering New DataFrame for Generating Fresh Contact 'csv' File

In [13]:
New_Studs_Contact_list = pd.DataFrame()

In [14]:
type(New_Studs_Contact_list)

pandas.core.frame.DataFrame

#### Merging all the Different Sections files into Single Dataframe

In [15]:
Apex21BDA = pd.concat([Apex21BDA1,Apex21BDA2,Apex21BDA3], ignore_index=True)

In [16]:
Apex21BDA = Apex21BDA.rename(columns={"Student Name" : "Name"})

In [19]:
Apex21BDA = Apex21BDA.rename(columns={'Student UID':'Stud_UID'})

In [20]:
Apex21BDA.head()

   Sr. No             Name   Stud_UID    Section Group  Mobile Number
0       1  Tamanpreet Kaur  20BCS3754  20AITBDA1     A        8679508
1       2       Akash Siby  20BCS3757  20AITBDA1     A        8679508
2       3     Aditya Arora  20BCS3758  20AITBDA1     A        8679508
3       4      Iram Nishat  20bcs3761  20AITBDA1     A        8679508
4       5  Karan Bhandari   20BCS3763  20AITBDA1     A        8679508

#### Below Conversion of Strings to any Common case is mandetory for proper comparision

In [30]:
Apex21BDA["Name"]= Apex21BDA["Name"].str.upper()
Non_RegisteredStuds["Name"] = Non_RegisteredStuds["Name"].str.upper()

In [31]:
Apex21BDA["Name"].head()

0    TAMANPREET KAUR
1         AKASH SIBY
2       ADITYA ARORA
3        IRAM NISHAT
4    KARAN BHANDARI
Name: Name, dtype: object

In [32]:
Non_RegisteredStuds["Name"].head()

0         BHAVIK JAIN
1        MUKESH KUMAR
2    DRISHTI VASHISTH
3        SAGAR GROVER
4         TARUN BISHT
Name: Name, dtype: object

#### Checking the Size of Dataframes that are to be compared

In [33]:
len(Apex21BDA)

230

In [34]:
len(Non_RegisteredStuds)

55

#### performing INNER_JOIN on the both Dataframes

In [41]:
New_Studs_Contact_list = Apex21BDA.merge(Non_RegisteredStuds, left_on="Name", right_on="Name", how="right")

In [42]:
#New_Studs_Contact_list = Apex20BDA.merge(Non_RegisteredStuds,left_on='Name', right_on='Name', how='inner')

In [43]:
New_Studs_Contact_list

,Sr. No,Name,Stud_UID,Section,Group,Mobile Number,Acct. No,Father Name,City,Program Name,Academic Registered,hostel Name,Room No,Hostel Reported,Final Status,Unnamed: 10,Unnamed: 11
0,4.0,IRAM NISHAT,20bcs3761,20AITBDA1,A,8679508.0,12002946,Sekh Israfil,Bankura,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
1,7.0,AMIT KUMAR,20bcs3767,20AITBDA1,A,8679508.0,12028065,PANCHAM YADAV,Madhepura,Bachelor of Engineering in Computer Science an...,Non-Registered,Lecorbusier Block D,502-C,Non-Reported,Non-Registered,NaN,Not lifted call
2,48.0,AMIT KUMAR,20BCS4455,20AITBDA3,B,24913.0,12028065,PANCHAM YADAV,Madhepura,Bachelor of Engineering in Computer Science an...,Non-Registered,Lecorbusier Block D,502-C,Non-Reported,Non-Registered,NaN,Not lifted call
3,11.0,VIKASH KUMAR MISHRA,20BCS3785,20AITBDA1,A,8679508.0,12012104,ANIL KUMAR MISHRA,Samastipur,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 5,811-C,Non-Reported,Non-Registered,NaN,NaN
4,20.0,SAGAR GROVER,20BCS3802,20AITBDA1,A,8679508.0,12006710,SATISH KUMAR,Chandigarh,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
5,42.0,ABHAY SINGH MANHAS,20BCS3843,20AITBDA1,B,8679508.0,12017259,DALEEP SINGH,Jammu,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
6,46.0,ARYAN,20BCS3847,20AITBDA1,B,8679508.0,12017940,SANJEEV,Gurgaon,Bachelor of Engineering in Computer Science an...,Non-Registered,Lecorbusier Block A,510-A,Non-Reported,Non-Registered,NaN,Registered on 19th July
7,7.0,ARYAN,20bcs3912,20AITBDA2,A,7250379.0,12017940,SANJEEV,Gurgaon,Bachelor of Engineering in Computer Science an...,Non-Registered,Lecorbusier Block A,510-A,Non-Reported,Non-Registered,NaN,Registered on 19th July
8,65.0,ASHUTOSH KUMAR,20BCS3882,20AITBDA1,B,8679508.0,12000466,ARVIND KUMAR,Muzaffarpur,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 5,613-C,Non-Reported,Non-Registered,NaN,Registered
9,71.0,ASHUTOSH KUMAR,20BCS4359,20AITBDA2,B,7250379.0,12000466,ARVIND KUMAR,Muzaffarpur,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 5,613-C,Non-Reported,Non-Registered,NaN,Registered
10,67.0,AKSHAT SHRIVASTAVA,20BCS3888,20AITBDA1,B,8679508.0,12018667,SUNIL KUMAR SHRIVASTAVA,Gwalior,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 5,702-D,Non-Reported,Non-Registered,NaN,NaN
11,14.0,SHIVESH PUSHP,20BCS3925,20AITBDA2,A,7250379.0,12021804,MANOJ KUMAR,Patna,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 4,803-C,Non-Reported,Non-Registered,NaN,Not lifted call
12,33.0,TARUN BISHT,20BCS3949,20AITBDA2,A,7250379.0,12022639,DEEP SINGH,Chandigarh,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifted Call
13,36.0,KAMIREDDY RAJASEKHAR REDDY,20BCS3953,20AITBDA2,A,7250379.0,12022664,KAMIREEDY RAMACHANDRA REDDY,Hyderabad,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 5,601-C,Non-Reported,Non-Registered,NaN,Registered
14,38.0,MANMOHAN MISHRA,20bcs3957,20AITBDA2,A,7250379.0,12022487,RISHIKESH MISHRA,Deoria,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Switched Off
15,40.0,AMNINDER SINGH,20BCS3959,20AITBDA2,B,7250379.0,12022964,SUKHJEET SINGH,Bagha Purana,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifting Call
16,53.0,MUKUL KUMAR SINGH,20BCS3978,20AITBDA2,B,7250379.0,12022990,MEDANI MOHAN SINGH,Katihar,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Mom Not Understanding English
17,56.0,VAIBHAV AGARWAL,20BCS3983,20AITBDA2,B,7250379.0,12023401,Radha raman gupta,Jaipur,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 1,824-A,Non-Reported,Non-Registered,NaN,Out Of Coverage
18,57.0,AYUSH KUMAR JHA,20BCS3985,20AITBDA2,B,7250379.0,12023133,PREM KUMAR JHA,Haridwar,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifted call
19,58.0,GAURAV KUMAR TIWARY,20bcs3986,20AITBDA2,B,7250379.0,12022573,Pradeep tiwary,Daltonganj,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,"Financial Issues , Will pay fee in 2-3 days"
20,63.0,VIDUSH GAUTAM,20BCS3997,20AITBDA2,B,7250379.0,12023761,VIPIN KUMAR,Faridabad,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,waiting for Loan Approval
21,64.0,MUKESH KUMAR,20BCS3998,20AITBDA2,B,7250379.0,12007223,BRIJ BIHARI SINGH,Patna,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifted Call
22,9.0,BHAVIK JAIN,20BCS4380,20AITBDA3,A,24874.0,12023896,Dilip jain,Raipur,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 3,523-C,Non-Reported,Non-Registered,NaN,"Asking for Fee pay in Installments, Bcoz Not A..."
23,15.0,APEKSHA GUPTA,20bcs4390,20AITBDA3,A,24880.0,12023795,desh bandhu gupta,Alwar,Bachelor of Engineering in Computer Science an...,Non-Registered,Tagore B,705-D,Non-Reported,Non-Registered,NaN,Not lifted call
24,18.0,SUJEET SHARMA,20BCS4399,20AITBDA3,A,24883.0,12025225,PRAMOD SHARMA,West Champaran,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,"Financial Issues, mailed regarding"
25,22.0,ISHAN ARORA,20BCS4411,20AITBDA3,A,24887.0,12019493,VIJAY KUMAR ARORA,Maihar,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifting Call
26,29.0,KSHITIJ TYAGI,20BCS4421,20AITBDA3,A,24894.0,12026043,NEERAJ TYAGI,Alwar,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Waiting for Loan approval from bank
27,39.0,POOJA VERMA,20BCS4439,20AITBDA3,A,24904.0,12023151,Om prakash,Khategaon,Bachelor of Engineering in Computer Science an...,Non-Registered,Tagore A,513-B,Non-Reported,Non-Registered,NaN,Loan Issues -Can't afford to pay Fee..
28,45.0,KONNI SAI KRISHNA,20BCS4448,20AITBDA3,B,24910.0,12027490,KONNI POLAIAH,Srikakulam,Bachelor of Engineering in Computer Science an...,Non-Registered,Zakir B,1103-B,Non-Reported,Non-Registered,NaN,Scholorship Issues Waiting for Reply
29,49.0,ROHAN MISHRA,20BCS4456,20AITBDA3,B,24914.0,12008117,SHLOKI PRASAD MISHRA,"Som, Uttar Pradesh",Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifted Call
30,52.0,VISHAL SAXENA,20BCS4459,20AITBDA3,B,24917.0,12024990,SANJEEV SAXENA,Rudrapur,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,will pay within 2 days
31,56.0,HARSH RANA,20BCS4469,20AITBDA3,B,24921.0,12028436,DEVENDER KUMAR,Hamirpur,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not lifted call
32,57.0,GAURAV SUMAN,20BCS4471,20AITBDA3,B,24922.0,12028437,Rajesh kumar,Nalanda,Bachelor of Engineering in Computer Science an...,Non-Registered,Lecorbusier Block D,611-D,Non-Reported,Non-Registered,NaN,Waiting for Loan Sanction
33,59.0,UTKARSH RASTOGI,20BCS4474,20AITBDA3,B,24924.0,12028675,Sharad Kumar Rastogi,"Rampur, Uttar Pradesh",Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 3,504-A,Non-Reported,Non-Registered,NaN,Paid Fee & Will get Register
34,NaN,DRISHTI VASHISTH,NaN,NaN,NaN,NaN,12022636,Rajesh Sharma,Panchkula,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,Not Connecting
35,NaN,UMA SHANKAR SINGH,NaN,NaN,NaN,NaN,12013848,MOHAN SINGH,Madhubani,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
36,NaN,MUKKA SANTHOSH NARASIMHA,NaN,NaN,NaN,NaN,12025450,MUKKA HARISH KUMAR,Karimnagar,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
37,NaN,P VINAY KUMAR,NaN,NaN,NaN,NaN,12028316,P DESHMANTHA REDDY,Siddipet,Bachelor of Engineering in Computer Science an...,Non-Registered,Zakir B,1026-A,Non-Reported,Non-Registered,NaN,NaN
38,NaN,SAKSHAM BHATIA,NaN,NaN,NaN,NaN,12025019,SANJAY BHATIA,Faridabad,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
39,NaN,PERUKA RISHWANTH,NaN,NaN,NaN,NaN,12027953,PERUKA RAMESH,Karimnagar,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
40,NaN,SAKSHAM KOCHHAR,NaN,NaN,NaN,NaN,12023550,RAJIV KOCHHAR,Delhi,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 6,303-B,Non-Reported,Non-Registered,NaN,Paid Fee
41,NaN,NAMAN GOYAL,NaN,NaN,NaN,NaN,12022913,VIJAY GOYAL,Delhi,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 5,616-A,Non-Reported,Non-Registered,NaN,NaN
42,NaN,ANUSHKA JOSHI,NaN,NaN,NaN,NaN,12018529,ANOOP JOSHI,Mandsaur,Bachelor of Engineering in Computer Science an...,Non-Registered,Tagore B,401-C,Non-Reported,Non-Registered,NaN,Not lifted call
43,NaN,SUMIT CHOUDHARY,NaN,NaN,NaN,NaN,12001733,SWARN SINGH,Jammu,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
44,NaN,ABHIJEET ANAND,NaN,NaN,NaN,NaN,12022036,DHANANJAY KUMAR,Nalanda,Bachelor of Engineering in Computer Science an...,Non-Registered,Lecorbusier Block D,617-A,Non-Reported,Non-Registered,NaN,Waiting for Reply from Scholorship Issue
45,NaN,BILLALA NAVEEN REDDY,NaN,NaN,NaN,NaN,12018103,BILLALA VENKAT REDDY,Nalgonda,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 2,803-B,Non-Reported,Non-Registered,NaN,NaN
46,NaN,KARAN BHANDARI,NaN,NaN,NaN,NaN,12004819,RAJENDER BHANDARI,Faridabad,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
47,NaN,AMRIT SUSHIL,NaN,NaN,NaN,NaN,12016604,Bishwajit Kumar Sinha,Patna,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
48,NaN,MOHINISH SANJOWA,NaN,NaN,NaN,NaN,12026921,Ombir,Bijnor,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
49,NaN,PITTALA ARAVIND,NaN,NaN,NaN,NaN,12026169,PITTALA KUMARASWAMY,Warangal urban,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
50,NaN,KANCHARAPALLI TARA PRANAY,NaN,NaN,NaN,NaN,12025241,KANCHARAPALLI VEKATA RAMANA,Ramagundam,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
51,NaN,BHARAT YADAV,NaN,NaN,NaN,NaN,12029586,Jaipal Yadav,Alwar,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
52,NaN,JATIN KUMAR SAINI,NaN,NaN,NaN,NaN,12027321,Subhash Kumar Saini,Jhunjhunu,Bachelor of Engineering in Computer Science an...,Non-Registered,-,-,Day-Scholar,Non-REgistered,NaN,NaN
53,NaN,R AKSHAY,NaN,NaN,NaN,NaN,12021782,B RAGHUNATH,Delhi,Bachelor of Engineering in Computer Science an...,Non-Registered,Lecorbusier Block B,517-D,Non-Reported,Non-Registered,NaN,NaN
54,NaN,NAHEEL MOHAMMED,NaN,NaN,NaN,NaN,12025438,SAHOOD,Kochi,Bachelor of Engineering in Computer Science an...,Non-Registered,Zakir A,923-D,Non-Reported,Non-Registered,NaN,NaN
55,NaN,BHARTI MALIK,NaN,NaN,NaN,NaN,12024921,Bhawani Malik,Muzaffarnagar,Bachelor of Engineering in Computer Science an...,Non-Registered,Tagore A,614-D,Non-Reported,Non-Registered,NaN,Waiting for Reply from Scholorship Dept
56,NaN,GAURAV VERMA,NaN,NaN,NaN,NaN,12029256,HARIOM VERMA,Firozabad,Bachelor of Engineering in Computer Science an...,Non-Registered,Nek Chand Tower 5,806-A,Non-Reported,Non-Registered,NaN,Registered
57,NaN,HARSH KUMAR DEO,NaN,NaN,NaN,NaN,12025149,AVINASH KUMAR DEO,Supaul,Bachelor of Engineering in Computer Science an...,Non-Registered,Zakir A,717-E,Non-Reported,Non-Registered,NaN,NaN

In [37]:
len(New_Studs_Contact_list)

34

In [38]:
New_Studs_Contact_list.to_csv(root_path+'Non_Reg_Studs_Contacts_34_Rough.csv')